### ISSUE TITLE
Remove the option to use the plugin without registered data

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainglobe-segmentation#155]
Currently users can use the `Load atlas` functionality to use the plugin without registered data (just annotating on top of the atlas). Now we have `brainrender-napari` it's not clear what this adds really. 

@alessandrofelder shall we just remove this and simplify the plugin?

We would also need to update [the docs](https://brainglobe.info/documentation/brainglobe-segmentation/user-guide/index.html#to-load-your-data).

This would also mean we can close https://github.com/brainglobe/brainglobe-segmentation/issues/91

**Comment by alessandrofelder** [comment]
> shall we just remove this and simplify the plugin?
Yup
