### ISSUE TITLE
[Feature] move to `numpy 2`

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/brainglobe-segmentation#188]
**Is your feature request related to a problem? Please describe.**
We had to pin to `numpy<2` because of `hdf5` issues and we wanted to make a release in #187 

```
  tests/conftest.py:46: in segmentation_widget_with_data_atlas_space
      segmentation_widget.load_brainreg_directory()
  brainglobe_segmentation/segment.py:345: in load_brainreg_directory
      self.track_seg.check_saved_track()
  brainglobe_segmentation/segmentation_panels/tracks.py:228: in check_saved_track
      add_existing_track_layers(
  brainglobe_segmentation/tracks/layers.py:20: in add_existing_track_layers
      points = pd.read_hdf(track_file)
  .tox/py310/lib/python3.10/site-packages/pandas/io/pytables.py:426: in read_hdf
      store = HDFStore(path_or_buf, mode=mode, errors=errors, **kwargs)
  .tox/py310/lib/python3.10/site-packages/pandas/io/pytables.py:566: in __init__
      tables = import_optional_dependency("tables")
  .tox/py310/lib/python3.10/site-packages/pandas/compat/_optional.py:135: in import_optional_dependency
      module = importlib.import_module(name)
  /opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/importlib/__init__.py:126: in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
  .tox/py310/lib/python3.10/site-packages/tables/__init__.py:44: in <module>
      from .utilsextension import get_hdf5_version as _get_hdf5_version
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  
  >   ???
  E   ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
  
  tables/utilsextension.pyx:1: ValueError
  ---------------------------- Captured stdout setup -----------------------------
```
from https://github.com/brainglobe/brainglobe-segmentation/actions/runs/10256113259/job/28374581518

**Describe the solution you'd like**
We should be able to depend on `numpy>=2`.

**Describe alternatives you've considered**

\

**Additional context**
@IgorTatarnikov suspects that this is due to either `pandas` or `h5py` + `numpy>=2` compatibility, from a look at SO: https://stackoverflow.com/questions/78634235/numpy-dtype-size-changed-may-indicate-binary-incompatibility-expected-96-from or maybe `pytables`

**Comment by alessandrofelder** [comment]
Newest `tables==3.10` fixes this incompatibility in an env with `numpy=2.0.1`, but its `pypi` version still enforces `numpy<2` - hopefully fixed soon so we can upgrade: https://github.com/PyTables/PyTables/issues/1200

**Comment by adamltyson** [comment]
When this is updated we will also need to remove the restriction on the conda-forge package. I've pinned it temporarily in https://github.com/conda-forge/brainglobe-segmentation-feedstock/pull/10
