### ISSUE TITLE
output total probe track distance (from surface to last point in track)

### ISSUE THREAD

**Issue by takacsflora** [brainglobe/brainglobe-segmentation#37]
Hi, it would be great if total probe track distance (from surface to last point in track) could be outputted, as sometimes it is hard to know during insertion how deep I inserted the probe, and then equally distributed sampling does not help. (That is I insert 5 mm into the brain and I record the 3mm at the tip, but I am not confident that I inserted exactly 5mm). Thank you!!

**Comment by adamltyson** [comment]
I can add this, but it would only make sense for the analysis in sample space, and not atlas space.

**Comment by takacsflora** [comment]
Oh I see - so then I could determine the insertion depth in sample space and then sample according to that depth every n samples in atlas space if needed.

**Comment by adamltyson** [comment]
To retain the idea of `brainreg-segment` being a general purpose tool, the best way is just to report the length of the spline fit. Whether this would be from the brain surface or not would depend on if the `Add surface points` has been used.

**Comment by adamltyson** [comment]
Not sure where this could be reported. Could be:
* In the user interface
* A separate file
* An additional column in the existing output, possibly also reporting the distance along the probe at each point of the fit.

**Comment by adamltyson** [comment]
If we go for adding an additional column, should be able to do something like this:

```python
from scipy.spatial.distance import euclidean


def get_distances(spline, voxel_size=10):
    distances = []
    for i in range(len(spline) - 1):
        distance = euclidean(spline[i], spline[i + 1]) * voxel_size 
        distances.append(distances[i] + distance)
    return distances
