### ISSUE TITLE
[Feature] Improve experience when loading atlases

### ISSUE THREAD

**Issue by dstansby** [brainglobe/brainglobe-segmentation#91]
**Is your feature request related to a problem? Please describe.**
Every time I go to load an atlas with `brainreg-segment`, I'm propted with a file browser to choose a directory. This has two issues:
1. It's not clear what the file browser is for. Is it where the data is downloaded to? Am I meant to select a directory that contains an already downloaded atlas?
2. If I load the same atlas twice (perhaps in different napari sessions), I still have to navigate the file browser the second time.

**Describe the solution you'd like**
1. Some UI info on what the file browser is for
2. Once I've loaded one atlas, however I've loaded it, I would expect `brainreg-segment` to remember where it is so I don't have to repeatedly navigate a file browser every time I want to load an atlas.

**Describe alternatives you've considered**

**Additional context**

**Comment by adamltyson** [comment]
Hmm, need to improve [the docs here](https://docs.brainglobe.info/brainreg-segment/user-guide#to-load-your-data).

Loading an atlas in `brainreg-segment` doesn't have much of a purpose. It's there so users can use the plugin without having their own data. The directory selected is where the outputs of the plugin will be saved. "Normally" a brainreg output directory is loaded, and the brainreg-segment outputs are saved there too.

**Comment by adamltyson** [comment]
Alternatively, we could just remove this option entirely. brainreg-segment shouldn't be the plugin where users can just visualise an atlas, that will be taken care of eventually by [brainglobe-napari](https://github.com/brainglobe/brainglobe-napari).

**Comment by adamltyson** [comment]
Closing this as we have removed this function from the plugin entirely.
